import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './components/App';
//import DataComponent from './components/DataComponent';
import { BrowserRouter } from 'react-router-dom';
import "./components/indexList.css";
import Footer from "./components/Footer";
import reportWebVitals from "./components/reportWebVitals";
import MultiCarousel from "./components/MultiCarousel";
import Navbar from './components/Navbar';
import ThumbnailViewer from './components/ThumbnailViewer';
import ArticlesIntro from './routes/ArticlesIntro';
import './App.css';
import './App.scss';
import { Link } from 'react-router-dom';


const pdfList = [
  {id: 1, pdfUrl: '/ebooks/Engineering Intelligent Systems.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Barclay R. Brown', description: 'Systems Engineering and Design with Artificial Intelligence, Visual Modeling, and Systems Thinking.' },
  {id: 2, pdfUrl: '/ebooks/impatient-js-preview-book.pdf', bookTitle: 'JavaScript For Impatient Programmers ECMAScript 2022 Edition', author: 'Dr. Axel Rauschmayer', description: 'An exhaustive resource, yet cuts out the fluff that clutters many programming books – with explanations that are understandable and to the point, as promised by the title! The quizzes and exercises are a very useful feature to check and lock in your knowledge. And you can definitely tear through the book fairly quickly, to get up and running in JavaScript.' },
  {id: 3, pdfUrl: '/ebooks/A Practical Introduction To Python Programming Heinold.pdf', bookTitle: 'A Practical Introduction to Python Programming', author: 'Brian Heinold', description: 'Though this book was designed to be used in an introductory programming course, it is also useful for those with prior programming experience looking to learn Python. If you are one of those people, you should be able to breeze through the first several chapters. You should find Part II to be a concise, but not superficial, treatment on GUI programming. Part III contains information on the features of Python that allow you to accomplish big things with surprisingly little code.' },
  {id: 4, pdfUrl: '/ebooks/Python 3 Using ChatGPT- GPT-4.pdf', bookTitle: 'Python 3 Using ChatGPT / GPT-4', author: 'Oswald Campesato', description: 'This book is intended primarily for people who want to learn both Python and how to use ChatGPT with Python. This book is also intended to reach an international audience of readers with highly diverse backgrounds in various age groups. In addition, it uses standard English rather than colloquial expressions that might be confusing to those readers. This book provides a comfortable and meaningful learning experience for the intended readers.' },
  {id: 5, pdfUrl: '/ebooks/React_Hooks_Guided_Tour.pdf', bookTitle: 'React Hooks A Guided Tour', author: 'Dave Ceddia', description: 'https://daveceddia.com/hooks' },
  {id: 6, pdfUrl: '/ebooks/SOFTWARE ARCHITECH-MICHAEL BELL.pdf', bookTitle: 'SOFTWARE ARCHITECH', author: 'MICHAEL BELL', description: 'As a software architect you\'ve embarked on a career journey in an unchartered and unpredictable territory with no guarantee of successful technological solutions. You are employed as a software architect to participate in a corporate business, technological, and social experiment whose chief thrust is to manufacture software products deployed to virtual environments. It\'s also arduous to foretell the business performance quality and stability after deploying and integrating software implementations in computing ecosystems.' },
  {id: 7, pdfUrl: '/ebooks/React and Static web.pdf', bookTitle: '50 Projects For React And The Static Web', author: 'Colby Fayock', description: 'This resource is your guide to project ideas to help push your coding journey. Some of the projects like building a website, creating a custom hook, and adding search to your existing website will help give you motivation for ways to learn by doing.' },
  {id: 8, pdfUrl: '/ebooks/Machine Learning_ Step-by-Step Guide.pdf', bookTitle: 'Machine Learning-Step-by-Step Guide To Implement Machine Learning Algorithms with Python 8', author: 'Rudolph Russell', description:'Machine learning is the practice of programming computers to learn from data.In reality t, machine learning is involved not only in robotics, but also in many other applications. You can also imagine something like a spam filter as being one of the first applications in machine learning, which helps improve the lives of millions of people.' },
  {id: 9, pdfUrl: '/ebooks/30-Days-Of-React-An -Intro-To-React-In-30-Bite-Sized-Morsels.pdf', bookTitle: '30 Days Of React-An Intro To React In 30 Bite-Sized Morsels', author: 'Written by Fullstack.io and friends', description: 'Grasp adequate information to write some very complex applications, integrated with data, styled to perfection, tested and deployed with this 30 day in-depth intro to React.' },
  {id: 10, pdfUrl: '/ebooks/React and Static web.pdf', bookTitle: '50 Projects For React And The Static Web', author: 'Colby Fayock', description: 'This resource is your guide to project ideas to help push your coding journey. Some of the projects like building a website, creating a custom hook, and adding search to your existing website will help give you motivation for ways to learn by doing.' },
  {id: 11, pdfUrl: '/ebooks/A Practical Introduction To Python Programming Heinold.pdf', bookTitle: 'A Practical Introduction to Python Programming', author: 'Brian Heinold', description: 'Though this book was designed to be used in an introductory programming course, it is also useful for those with prior programming experience looking to learn Python. If you are one of those people, you should be able to breeze through the first several chapters. You should find Part II to be a concise, but not superficial, treatment on GUI programming. Part III contains information on the features of Python that allow you to accomplish big things with surprisingly little code.' },
  {id: 12, pdfUrl: '/ebooks/Advanced Data Structures-Lecture.pdf', bookTitle: 'II B.tech II semester Lecture notes on ADVANCED DATA STRUCTURES', author: 'Prepared by Mr PVenkateswarlu Assistant professor Department of information technology', description: 'Touches on data as the basic entity of fact that is used in calculations or manipulating processes.The way of organizing the data & performing the operations to highlight the important concept of data structures.' },
  {id: 13, pdfUrl: '/ebooks/AI-With-Java.pdf', bookTitle: 'Practical Artificial Intelligence Programming With Java Third Edition', author: 'Mark Watson', description: 'I wrote this book for both professional programmers and home hobbyists who already know how to program in Java and who want to learn practical Artificial Intelligence (AI) programming and information processing techniques. I have tried to make this an enjoyable book to work through. In the style of a “cook book,” the chapters can be studied in any order. Each chapter follows the same pattern: a motivation for learning a technique, some theory for the technique, and a Java example program that you can experiment with.' },
  {id: 14, pdfUrl: '/ebooks/Beginning-React-with-Hooks-by-Lim-Greg-z-lib.pdf', bookTitle: 'Beginning React with Hooks', author: 'Greg Lim', description: 'In this book, we take you on a fun, hands-on and pragmatic journey to master React Hooks from a web development point of view. You\'ll start building React apps using functional components within minutes. Every section is written in a bite-sized manner and straight to the point as I don’t want to waste your time (and most certainly mine) on the content you don\'t need. In the end, you will have what it takes to develop a real-life app.' },
  {id: 15, pdfUrl: '/ebooks/An Intro To Functional Programming Through Lambda Calculus.pdf', bookTitle: 'AN INTRODUCTION TO FUNCTIONAL PROGRAMMING THROUGH LAMBDA CALCULUS', author: 'Greg Michaelson, Department of Computing and Electrical Engineering Heriot-Watt University Riccarton Campus Edinburgh EH14 4AS', description: 'This book aims to provide a gentle introduction to functional programming. It is based on the premises that functional programming provides pedagogic insights into many aspects of computing and offers practical techniques for general problem solving.The approach taken is to start with pure l calculus, Alonzo Church’s elegent but simple formalism for computation, and add syntactic layers for function definitions, booleans, integers, recursion, types, characters, lists and strings to build a highish level functional notation. Along the way, a variety of topics are discussed including arithmetic, linear list and binary tree processing, and alternative evaluation strategies. Finally, functional programming in Standard ML and COMMON LISP, using techniques developed throughout the book, are explored.Readership<br /> This book is intended for people who have taken a first course in an imperative programming language like Pascal,FORTRAN or C and have written programs using arrays and sub-programs. There are no mathematical prerequisites and no prior experience with functional programming is required.' },
  {id: 16, pdfUrl: '/ebooks/Cheat-Sheet-Xebla.pdf', bookTitle: 'REACT HOOKS CHEAT SHEETS', author: '', description: 'REACT HOOKS CHEAT SHEETS-Xebla' },
  {id: 17, pdfUrl: '/ebooks/Full Stack AngularJS for Java Developers.pdf', bookTitle: 'Full Stack AngularJS for Java Developers', author: 'Ravi Kant Soni', description: 'Build a Full-Featured Web Application from Scratch Using AngularJS with Spring RESTful API.Full stack web development lets you explore the best tools and frameworks while making your application solid and reliable on different fronts such as design, scalability, robustness, and security.' },
  {id: 18, pdfUrl: '/ebooks/Graphql_Tutorial.pdf', bookTitle: 'GraphQL', author: 'Tutorials Point', description: 'This tutorial is created for developers who have worked on JavaScript applications based on Client-Server architecture. After completing this tutorial, you will be able to build moderately complex GraphQL APIs for mobile and web applications.' },
  {id: 19, pdfUrl: '/ebooks/Java Development Hands-on Training Program.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 19' },
  {id: 20, pdfUrl: '/ebooks/Learn Java for Web Development.pdf', bookTitle: 'Learn Java For Web Development', author: 'Vishal Layka', description: 'This book is for a large cross-section of modern Java wweb developers, with various levels of experience.This book addresses all the needs of a modern Java web developer. It is designed for beginners up to intermediate developers and explains the specifics of Java on the Web. For example, this book is perfect for developers who are aware of technologies like MVC but do not yet understand how and why they have changed the way web applications are built.This book is also for developers who want to learn frameworks other than JSF 2 (which is bundled with Java EE). This book covers four types of web frameworks: request based, component based,rapid, and reactive. Among these four types, the book covers five proven web frameworks: Struts 2, Spring Web MVC, JSF 2, Grails 2, and Play 2.In addition, this book is for developers who have no experience in the Java, Groovy, and Scala programming languages but who yearn to create web applications. This book provides the essentials of these three languages in the appendixes.' },
  {id: 21, pdfUrl: '/ebooks/Learn Java With Projects.pdf', bookTitle: 'Learn Java with Projects A concise practical guide to learning everything a Java professional really needs to know.', author: 'Dr. Sean Kennedy, Maaike van Putten',description: 'Dr. Sean Kennedy is a university lecturer with over 20 years of experience in teaching. He has a Ph.D. in IT and is Oracle-certified in Java at the Professional level (OCP). In his daily work, he has taught Java on Ericssons’ bespoke Master’s program for over a decade. He has several very popular Java courses on Udemy, one of which, Java 21, Java 17, Java 11, Advanced Java 8, has been selected for inclusion in their Udemy Business program (where only the top 3% of courses qualify). He has a YouTube channel called Let’s Get Certified that teaches Java at all levels and prepares candidates for Java certification. Outside of work, he enjoys tennis, walking, reading, TV, and nature. Maaike van Putten is a software consultant and trainer with a passion for empowering others in their careers. Her love for Java shows in numerous software development projects she participated in and the 5 Oracle Java certifications she obtained. She has designed and delivered a broad spectrum of training courses catering to beginners and seasoned developers in Java and many other languages and frameworks. Next to that, she has authored multiple books and online courses through multiple platforms reaching over 600,000 learners.' },
  {id: 22, pdfUrl: '/ebooks/Learn NodeJS in 1 Day_ Complete Node  JS Guide with Examples.pdf', bookTitle: 'Learn NodeJS in 1 Day', author: 'Krishna Rungta', description: 'The modern web application has really come a long way over the years with the introduction of many popular frameworks such as bootstrap, Angular JS, etc. All of these frameworks are based on the popular JavaScript framework. But when it came to developing server based applications there was just kind of a void, and this is where Node.js came into the picture. Node.js is also based on the JavaScript framework, but it is used for developing server-based applications. While going through the entire tutorial, we will look into Node.js in detail and how we can use it to develop server based applications.' },
  {id: 23, pdfUrl: '/ebooks/Mastering Machine Learning with Python in Six Steps.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 23' },
  {id: 24, pdfUrl: '/ebooks/Python Machine Learning.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 24' },
  {id: 25, pdfUrl: '/ebooks/React Interview Questions.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 25' },
  {id: 26, pdfUrl: '/ebooks/React Quickly_ Painless Web Apps with React, JSX, Redux and GraphQL.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 26' },
  {id: 27, pdfUrl: '/ebooks/React.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 27' },
  {id: 28, pdfUrl: '/ebooks/React_Hooks_Guided_Tour.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 28' },
  {id: 29, pdfUrl: '/ebooks/Reactjs-Daniel-Gasienica-Notes.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 29' },
  {id: 30, pdfUrl: '/ebooks/Robust Python-Patrick Viafore.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 30' },
  {id: 31, pdfUrl: '/ebooks/SOFTWARE ARCHITECH-MICHAEL BELL.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 31' },
  {id: 32, pdfUrl: '/ebooks/The Road to learn React_ Your journey to master plain yet pragmatic React.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 32' },
  {id: 33, pdfUrl: '/ebooks/Venkat Subramaniam - Functional Programming in Java (The Pragmatic Programmers) - 2014.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 33' },
  {id: 34, pdfUrl: '/ebooks/Web Animation using JavaScript_ Develop & Design.pdf', bookTitle: 'Engineering Intelligent Systems', author: 'Kofi', description: 'Description for Book 34' },
  {id: 35, pdfUrl: '/ebooks/20 UCaaS Providers You Should Know in 2024.pdf', bookTitle: '20 UCaaS Providers You Should Know in 2024', author: 'Kofi', description: 'Description for Book 35' },
  {id: 36, pdfUrl: '/ebooks/A Beginner’s Guide to Microsoft PowerShell.pdf', bookTitle: 'A Beginner’s Guide to Microsoft PowerShell', author: 'Kofi', description: 'Description for Book 36' },
  {id: 37, pdfUrl: '/ebooks/A LOOK BACK ON LONDON TECH WEEK 2021 AMPLIFYING THE POWER, RESILIENCE AND SPEED OF INNOVATION', bookTitle: 'A LOOK BACK ON LONDON TECH WEEK 2021 AMPLIFYING THE POWER, RESILIENCE AND SPEED OF INNOVATION', author: 'Kofi', description: 'Description for Book 37' },
  {id: 38, pdfUrl: '/ebooks/Email Etiquette Quick Reference Guide.pdf', bookTitle: 'Email Etiquette Quick Reference Guide', author: 'Kofi', description: 'Description for Book 38' },
  {id: 39, pdfUrl: '/ebooks/Technology in Small and Medium Sized Enterprises.pdf', bookTitle: 'Technology in Small and Medium Sized Enterprises', author: 'Kofi', description: 'Description for Book 39' },
  {id: 40, pdfUrl: '/ebooks/The Ultimate ChatGPT Cheat Sheet.pdf', bookTitle: 'The Ultimate ChatGPT Cheat Sheet', author: 'Kofi', description: 'Description for Book 40' },
  {id: 41, pdfUrl: '/ebooks/Uniting Business and Technology to Create a Better, More Inclusive Digital World-Africa tech Festival.pdf', bookTitle: 'Uniting Business and Technology to Create a Better, More Inclusive Digital World-Africa tech Festival', author: 'Kofi', description: 'Description for Book 41' },
  {id: 42, pdfUrl: '/ebooks/Learn Linux in 5 Days.pdf', bookTitle: 'Learn Linux in 5 Days', author: 'Kofi', description: 'Description for Book 42' },
  {id: 43, pdfUrl: '/ebooks/Find Cheat Sheet by Linux Training Academy.pdf', bookTitle: 'Find Cheat Sheet by Linux Training Academy', author: 'Kofi', description: 'Description for Book 43' },
  {id: 44, pdfUrl: '/ebooks/GIMP KEYBOARD SHORTCUTS.pdf', bookTitle: 'GIMP KEYBOARD SHORTCUTS', author: 'Kofi', description: 'Description for Book 44' },
  {id: 45, pdfUrl: '/ebooks/Cybersecurity Maximum attention, minimum budget – the carrot and the stick.pdf', bookTitle: 'Cybersecurity Maximum attention, minimum budget – the carrot and the stick', author: 'Kofi', description: 'Description for Book 45' },
  {id: 46, pdfUrl: '/ebooks/How To Make Money Blogging Online.pdf', bookTitle: 'How To Make Money Blogging Online', author: 'Kofi', description: 'Description for Book 46' },
  {id: 47, pdfUrl: '/ebooks/Cyber Threat Intelligence.pdf', bookTitle: 'Cyber Threat Intelligence', author: 'Kofi', description: 'Description for Book 47' },
  {id: 48, pdfUrl: '/ebooks/Generative AI Tips and Tricks for ChatGPT, Bard, Dall-E, and Midjourney.pdf', bookTitle: 'Generative AI Tips and Tricks for ChatGPT, Bard, Dall-E, and Midjourney', author: 'Kofi', description: 'Description for Book 48' }
  // Add more PDF objects as needed
];


const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
   
  <React.StrictMode>
  <div align="center"><MultiCarousel /><br /></div>
    <BrowserRouter>
	<div className="nav-area">
        <Link to="/" className="logo">         
        </Link>
		<br clear="all"/>
        <Navbar /></div>
		<div><App /></div>
        <div><ArticlesIntro /><br /></div>		
    </BrowserRouter>
	
	{/*<div align="center"><DataComponent /><br /></div>*/}
	<div align="center"><table width="80%"><ThumbnailViewer pdfList={pdfList} /></table></div>
    <Footer />
  </React.StrictMode>
);



// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

